// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnweg5lv3vSIfMhZbJDYddKB3yj8Jlbgw',
    appId: '1:988545861218:web:13af27b9d3b8b603be333b',
    messagingSenderId: '988545861218',
    projectId: 'krown-sushi',
    authDomain: 'krown-sushi.firebaseapp.com',
    storageBucket: 'krown-sushi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6C-9SswH_3Iau_CoGZ1Ij8Yc0pmHxgws',
    appId: '1:988545861218:android:4f4b59faae8f98ffbe333b',
    messagingSenderId: '988545861218',
    projectId: 'krown-sushi',
    storageBucket: 'krown-sushi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARippJTyusGPPS1uOiAhC0ZvfdTm5z_Dg',
    appId: '1:988545861218:ios:0eaf16e7f126669ebe333b',
    messagingSenderId: '988545861218',
    projectId: 'krown-sushi',
    storageBucket: 'krown-sushi.appspot.com',
    iosBundleId: 'com.example.krownSushi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARippJTyusGPPS1uOiAhC0ZvfdTm5z_Dg',
    appId: '1:988545861218:ios:5aa8bc34058d278ebe333b',
    messagingSenderId: '988545861218',
    projectId: 'krown-sushi',
    storageBucket: 'krown-sushi.appspot.com',
    iosBundleId: 'com.example.krownSushi.RunnerTests',
  );
}
